# History settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY       # Share history instantly
setopt HIST_IGNORE_DUPS    # Don't record a command if it's the same as the last
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS  # Trim extra whitespace
# Append to the history file, don't overwrite it
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY  # Write each command as soon as you run it
# Saner history behavior
setopt EXTENDED_HISTORY    # Save timestamp + duration
setopt HIST_VERIFY         # Don't execute event expansion immediately

# type name of directory to cd into it
setopt autocd

# For using output of commands in prompt
setopt PROMPT_SUBST

bindkey -v
bindkey '^R' history-incremental-search-backward

# Use home and end keys to jump to the beginning and end of line
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line

# Autocomplere commands
autoload -Uz compinit
compinit

# Aliases
alias vim=nvim
alias vi=nvim
alias v=nvim

alias ls='ls --color=auto'
alias ll='ls -la --color=auto'
alias la='ls -la --color=auto'

alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit -m '
alias gp='git push'
alias gl='git log'
alias gd='git diff'

alias pdf=zathura

alias shutdown='sudo shutdown -h now'
alias reboot='sudo shutdown -r now'
alias restart='sudo shutdown -r now'

# Set prompt
[ -f ~/dotfiles/zsh/zshprompt.sh ] && source ~/dotfiles/zsh/zshprompt.sh
[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export PATH=$PATH:~/bin/zig
